### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Semisol** [micahlt/sc4#1]
@micahlt I need your discord tag.

**Comment by micahlt** [comment]
@smileycreations15 I don't use Discord anymore.  :\

**Comment by Semisol** [comment]
:/ Okay.

**Comment by Semisol** [comment]
@micahlt  so can we keep this closed for general chat

**Comment by micahlt** [comment]
If necessary.  Unrelated stuff can go on Scratch.

**Comment by Semisol** [comment]
Okay.
